name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

          
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: consbio/mbtileserver.git
        path: .        
          
          
    - name: Build
      uses: sosedoff/actions/golang-build@master
      with:
          args: linux/amd64         
          
          
          

